### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Charlie-robin** [djava387/game-project#1]
# Feedback

## Requirements

- Pseudocode: DONE
- GitHub Repo:
  - README.md: DONE
  - 15 commits: Only 6 commits
- JS code formatted as functions: DONE
- JS code formatted with suitable variable names: DONE
- The code must be your own: DONE
- Click or key press events to trigger the game: DONE
  - No refreshing to start the game again: DONE
- Be responsive and built mobile-first, it should work on different screen widths: Built desktop first
- Deployed website: DONE

## Score

[MARKING-SCHEME](https://github.com/nology-tech/Augusta-Course-Resources/blob/main/student-resources/00-slides/02-js/game-marking-scheme.md)

| Category             | Score    |
| -------------------- | -------- |
| Site Output          | 30 / 40  |
| Code Knowledge & Use | 15 / 25  |
| Readability          | 15 / 20  |
| Responsiveness       | 10 / 15  |
| Total Score          | 70 / 100 |

# Feedback

### Positive

- You have a hosted and functioning javascript game this great, good going!
- I like that you have extended rock paper scissors by adding the additional options to it.
  - Having a simple functioning game like this is a good place to be!
  - You can always extend it by adding additional functionality.
- I like that you have taken on the feedback from your calculator and started to put your logic into their own functions.
  - `checkWinner` is a good example of this it takes parameters and returns a result. It doesn't do anything with the DOM meaning that you could write unit tests for this. Very nice :)
  - `playGame` Then uses this function gets the result and updates the HTML this shows a good understanding of functions.

### Constructive

- There are some points below you should resolve asap:

  - delete the unused & commented confetti code. You don't need it as you are using the CDN instead.
  - Rewrite your functions using arrow syntax.
    - e.g. `function playGame(e){ }` -> `const playGame = (e) => { }`
    - This is the modern way of writing functions. You want to get used to the syntax.
    - You will have to restructure your code slightly so you define your functions before you use them.

- The other points below are just about refactoring the code / adding features to it.
- I think you should add some information about the winning conditions.

  - It would be good to know what beats what e.g. paper covers rock, paper disproves Spock

- At the moment your `checkWinner` is quite busy, it is great that you got it working but that is when you want to refactor.
  - Where possible it is good to avoid having nested control flow. You can chain your checks together using `&&` and `||`. Sometimes it is unavoidable and that is okay in your case you can chain them see the example below.

```js
// app.js
function checkWinner(pl, co) {
  if (pl === co) {
    return "Draw";
  }
  if (pl === "Rock👊") {
    if (co === "Paper🖐" || co === "Spock🖖") {
      return "Mr. Robot";
    } else {
      return "You";
    }
  }
  if (pl === "Paper🖐") {
    if (co === "Scissors✌" || co === "Lizard🤏") {
      return "Mr. Robot";
    } else {
      return "You";
    }
  }
  if (pl === "Scissors✌") {
    if (co === "Rock👊" || co === "Spock🖖") {
      return "Mr. Robot";
    } else {
      return "You";
    }
  }
  if (pl === "Lizard🤏") {
    if (co === "Rock👊" || co === "Scissors✌") {
      return "Mr. Robot";
    } else {
      return "You";
    }
  }
  if (pl === "Spock🖖") {
    if (co === "Paper🖐" || co === "Lizard🤏") {
      return "Mr. Robot";
    } else {
      return "You";
    }
  }
}

// COULD BE

const checkWinner = (player, computer) => {
  if (player === computer) {
    return "Draw";
  }

  // YOU CAN AVOID NESTING YOUR IF STATEMENTS BY CHAINING YOUR CONDITIONS
  // USING BRACKETS WILL ALLOW YOU TO EVALUATE FIRST
  // THE CODE BELOW WOULD READ SOMETHING LIKE THIS 
  // IF FIRST-CONDITION IS TRUE AND (SECOND-CONDITION OR THIRD CONDITION) EITHER OF THESE ARE TRUE DO THE CODE
  if (player === "Rock👊" && (computer === "Paper🖐" || computer === "Spock🖖")) {
    return "Mr. Robot";
  }

  if (player === "Paper🖐" && (computer === "Scissors✌" || computer === "Lizard🤏")) {
    return "Mr. Robot";
  }

  if (player === "Scissors✌" && (computer === "Rock👊" || computer === "Spock🖖")) {
    return "Mr. Robot";
  }

  if (player === "Lizard🤏" && (computer === "Rock👊" || computer === "Scissors✌")) {
    return "Mr. Robot";
  }

  if (player === "Spock🖖" && (computer === "Paper🖐" || computer === "Lizard🤏")) {
    return "Mr. Robot";
  }

  // ALL OF YOUR ELSE STATEMENTS RETURN THE SAME THING SO YOU CAN JUST HAVE IT AS THE LAST RETURN
  // IF NONE OF THE CONDITIONS MATCHED ABOVE IT SHOULD MEAN THAT THE PLAYER HAS WON.
  return "You";
};
```

- At the moment the code above is still repetitive but is clearer and easier to read. I don't want to throw a lot of code at you so if you want to know how you can make this less repetitive just send me a message.

***

**Comment by djava387** [comment]
Thanks for the feedback!
